<?xml version="1.0" ?>
<!DOCTYPE Personal [
   <!ELEMENT Personal (email, contract, Donations, photo)>
   <!ATTLIST Personal name CDATA #REQUIRED
                      surname CDATA #REQUIRED>
   
   <!ELEMENT email (#PCDATA)>
   <!ELEMENT contract (id, salary, hours)>
   <!ELEMENT id (#PCDATA)>
   <!ELEMENT salary (#PCDATA)>
   <!ELEMENT hours (#PCDATA)>

   <!ELEMENT Donations (Donation*)>
   <!ELEMENT Donation (date, donor, nurse)>
   <!ATTLIST Donation amount CDATA #REQUIRED>
   
   <!ELEMENT date (#PCDATA)>
   
   <!ELEMENT donor (dob, BloodType+)>
   <!ATTLIST donor name CDATA #REQUIRED
                     surname CDATA #REQUIRED>
   
   <!ELEMENT dob (#PCDATA)>
   <!ELEMENT BloodType (#PCDATA)>
   
   <!ELEMENT nurse (email, contract, Donations, photo)>
   <!ATTLIST nurse name CDATA #REQUIRED
                    surname CDATA #REQUIRED>
   
   <!ELEMENT photo (#PCDATA)>
]>

<Personal name="Paco" surname="Vivas">
    <email>pacovivas@gmail.com</email>
    <contract>
        <id>1</id>
        <salary>50000</salary>
        <hours>40</hours>
    </contract>
    <Donations/>
    <photo>photos/paco.jpg</photo>
</Personal>