<?xml version="1.0" ?>
<!DOCTYPE Personal [
   <!ELEMENT Personal (email, contract, Donations)>
   <!ATTLIST Personal name CDATA #REQUIRED
                      surname CDATA #REQUIRED>
   
   <!ELEMENT email (#PCDATA)>
   <!ELEMENT contract (id, salary, hours)>
   <!ELEMENT id (#PCDATA)>
   <!ELEMENT salary (#PCDATA)>
   <!ELEMENT hours (#PCDATA)>

   <!ELEMENT Donations (Donation*)>
   <!ELEMENT Donation (date, donor, nurse)>
   <!ATTLIST Donation amount CDATA #REQUIRED>
   
   <!ELEMENT date (#PCDATA)>
   
   <!ELEMENT donor (dob, BloodType+)>
   <!ATTLIST donor name CDATA #REQUIRED
                     surname CDATA #REQUIRED>
   
   <!ELEMENT dob (#PCDATA)>
   <!ELEMENT BloodType (#PCDATA)>
   
   <!ELEMENT nurse (email, contract, Donations)>
   <!ATTLIST nurse name CDATA #REQUIRED
                     surname CDATA #REQUIRED>
]>

<Personal name="Paco" surname="Vivas">
    <email>pacovivas@gmail.com</email>
    <contract>
        <id>1</id>
        <salary>50000</salary>
        <hours>40</hours>
    </contract>
    <Donations>
        <Donation amount="50">
            <date>2024-05-01</date>
            <donor name="Maria" surname="Carrasco">
                <dob>1990-03-15</dob>
                <BloodType>A+</BloodType>
            </donor>
            <nurse name="Pepe" surname="Perez">
                <email>pepe@gmail.com</email>
                <contract>
                    <id>2</id>
                    <salary>60000</salary>
                    <hours>20</hours>
                </contract>
                <Donations/>
            </nurse>
        </Donation>
        <Donation amount="30">
            <date>2024-05-15</date>
            <donor name="Carmen" surname="Clar">
                <dob>1985-07-20</dob>
                <BloodType>O-</BloodType>
            </donor>
            <nurse name="Carlota" surname="Vivas">
                <email>carlotavivas@gmail.com</email>
                <contract>
                    <id>2</id>
                    <salary>60000</salary>
                    <hours>20</hours>
                </contract>
                <Donations/>
            </nurse>
        </Donation>
    </Donations>
</Personal>